pub(crate) mod ai_chat;
mod ai_prompts;
mod ai_providers;
pub(crate) mod ai_tools;
mod assignment;
mod audit;
mod auth;
mod chat;
mod chat_timing;
pub mod contabo;
pub mod contabo_domains;
pub mod coolify;
pub mod docker_stats;
pub mod email;
mod hosting_stripe;
pub mod image_processing;
mod note;
mod notification;
mod order;
mod payment;
mod payment_method;
mod seed;
mod vps_stripe;
mod wallet;

pub use ai_chat::{AiChatConfig, AiChatService, AiResponse, AiSessionContext};
pub use assignment::AssignmentService;
pub use audit::AuditService;
pub use auth::AuthService;
pub use chat::ChatHub;
pub use chat_timing::{ChatTimingService, RateCheckResult, TimingEvent, TimingSessionDeps};
pub use contabo::{ContaboConfig, ContaboService, CreateInstanceParams};
pub use coolify::{CoolifyConfig, CoolifyService};
pub use email::{EmailConfig, EmailService};
pub use hosting_stripe::{CheckoutParams, HostingStripeService};
pub use note::NoteService;
pub use notification::NotificationHub;
pub use order::OrderService;
pub use order::format_price_cents;
pub use payment::PaymentService;
pub use payment_method::PaymentMethodService;
pub use seed::SeedService;
pub use vps_stripe::{VpsCheckoutParams, VpsStripeService};
pub use wallet::WalletService;
