import {useQuery} from '@tanstack/react-query';
import {apiListPublicVpsPlans, type PublicVpsPlan} from '../api/hosting';

const VPS_PLANS_FALLBACK: PublicVpsPlan[] = [
    {
        tier_name: 'vps1',
        display_name: 'Cloud VPS 10',
        description: 'Entrada dedicada para automatizaciones, paneles internos y servicios pequeños con acceso root.',
        monthly_price_cents: 473,
        setup_fee_cents: 450,
        cpu_cores: 4,
        ram_mb: 8192,
        disk_mb: 76800,
        storage_type: 'NVMe',
        storage_options: ['75 GB NVMe', '150 GB NVMe', '150 GB SSD', '300 GB SSD'],
        port_speed_mbps: 200,
        bandwidth_label: 'Tráfico ilimitado con uso justo',
        snapshot_count: 1,
        region: 'EU',
        region_extra_cents: {},
        storage_extra_cents: {},
        features: ['4 vCPU dedicados', '8 GB RAM', '75 GB NVMe o 150 GB SSD', 'Puerto de 200 Mbit/s', 'Tráfico ilimitado con uso justo'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps2',
        display_name: 'Cloud VPS 20',
        description: 'Servidor balanceado para APIs, SaaS liviano y cargas sostenidas con más memoria.',
        monthly_price_cents: 882,
        setup_fee_cents: 0,
        cpu_cores: 6,
        ram_mb: 12288,
        disk_mb: 102400,
        storage_type: 'NVMe',
        storage_options: ['100 GB NVMe', '200 GB NVMe', '200 GB SSD', '400 GB SSD'],
        port_speed_mbps: 1000,
        bandwidth_label: 'Tráfico ilimitado con uso justo',
        snapshot_count: 2,
        region: 'EU',
        region_extra_cents: {},
        storage_extra_cents: {},
        features: ['6 vCPU dedicados', '12 GB RAM', '100 GB NVMe o 200 GB SSD', 'Puerto de 1 Gbit/s', 'Tráfico ilimitado con uso justo'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps3',
        display_name: 'VPS 30',
        description: 'Nodo dedicado para workloads medianos, workers concurrentes y aplicaciones con tráfico constante.',
        monthly_price_cents: 1764,
        setup_fee_cents: 0,
        cpu_cores: 8,
        ram_mb: 24576,
        disk_mb: 204800,
        storage_type: 'NVMe',
        storage_options: ['200 GB NVMe', '400 GB NVMe', '400 GB SSD', '800 GB SSD'],
        port_speed_mbps: 1000,
        bandwidth_label: 'Tráfico ilimitado con uso justo',
        snapshot_count: 3,
        region: 'EU',
        region_extra_cents: {},
        storage_extra_cents: {},
        features: ['8 vCPU dedicados', '24 GB RAM', '200 GB NVMe o 400 GB SSD', 'Puerto de 1 Gbit/s', 'Tráfico ilimitado con uso justo'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps4',
        display_name: 'VPS 40',
        description: 'Capacidad dedicada para pipelines pesados, bases de datos exigentes y servicios con mucha memoria.',
        monthly_price_cents: 3150,
        setup_fee_cents: 0,
        cpu_cores: 12,
        ram_mb: 49152,
        disk_mb: 256000,
        storage_type: 'NVMe',
        storage_options: ['250 GB NVMe', '500 GB NVMe', '500 GB SSD', '1000 GB SSD'],
        port_speed_mbps: 1000,
        bandwidth_label: 'Tráfico ilimitado con uso justo',
        snapshot_count: 3,
        region: 'EU',
        region_extra_cents: {},
        storage_extra_cents: {},
        features: ['12 vCPU dedicados', '48 GB RAM', '250 GB NVMe o 500 GB SSD', 'Puerto de 1 Gbit/s', 'Tráfico ilimitado con uso justo'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps5',
        display_name: 'VPS 50',
        description: 'Servidor de alta memoria para cargas intensivas, colas y stacks con varios servicios.',
        monthly_price_cents: 4673,
        setup_fee_cents: 0,
        cpu_cores: 16,
        ram_mb: 65536,
        disk_mb: 307200,
        storage_type: 'NVMe',
        storage_options: ['300 GB NVMe', '600 GB NVMe', '600 GB SSD', '1200 GB SSD'],
        port_speed_mbps: 1000,
        bandwidth_label: 'Tráfico ilimitado con uso justo',
        snapshot_count: 3,
        region: 'EU',
        region_extra_cents: {},
        storage_extra_cents: {},
        features: ['16 vCPU dedicados', '64 GB RAM', '300 GB NVMe o 600 GB SSD', 'Puerto de 1 Gbit/s', 'Tráfico ilimitado con uso justo'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps6',
        display_name: 'VPS 60',
        description: 'Capacidad máxima del catálogo VPS para workloads pesados y crecimiento sostenido.',
        monthly_price_cents: 6174,
        setup_fee_cents: 0,
        cpu_cores: 18,
        ram_mb: 98304,
        disk_mb: 358400,
        storage_type: 'NVMe',
        storage_options: ['350 GB NVMe', '700 GB NVMe', '700 GB SSD', '1400 GB SSD'],
        port_speed_mbps: 1000,
        bandwidth_label: 'Tráfico ilimitado con uso justo',
        snapshot_count: 3,
        region: 'EU',
        region_extra_cents: {},
        storage_extra_cents: {},
        features: ['18 vCPU dedicados', '96 GB RAM', '350 GB NVMe o 700 GB SSD', 'Puerto de 1 Gbit/s', 'Tráfico ilimitado con uso justo'],
        approval_required: true,
        recommended: false,
    },
];

export function useVpsCatalog() {
    const query = useQuery({
        queryKey: ['vps-public-plans'],
        queryFn: apiListPublicVpsPlans,
        staleTime: 5 * 60 * 1000,
    });

    return {
        plans: query.data ?? VPS_PLANS_FALLBACK,
        isLoading: query.isLoading,
        error: query.error,
    };
}