import {useQuery} from '@tanstack/react-query';
import {apiListPublicVpsPlans, type PublicVpsPlan} from '../api/hosting';

const VPS_PLANS_FALLBACK: PublicVpsPlan[] = [
    {
        tier_name: 'vps1',
        display_name: 'Cloud VPS 10',
        description: 'Entrada dedicada para automatizaciones, paneles internos y servicios pequeños con acceso root.',
        monthly_price_cents: 473,
        setup_fee_cents: 450,
        cpu_cores: 4,
        ram_mb: 8192,
        disk_mb: 76800,
        storage_type: 'NVMe',
        storage_options: ['75 GB NVMe', '150 GB NVMe', '150 GB SSD', '300 GB SSD'],
        port_speed_mbps: 200,
        bandwidth_label: 'Tráfico ilimitado',
        snapshot_count: 1,
        region: 'EU',
        region_extra_cents: {'EU': 0, 'UK': 95, 'US-EAST': 200, 'US-WEST': 200, 'SIN': 300, 'AUS': 300},
        storage_extra_cents: {'75 GB NVMe': 0, '150 GB NVMe': 185, '150 GB SSD': 0, '300 GB SSD': 155},
        features: ['4 vCPU dedicados', '8 GB RAM', '75 GB NVMe o 150 GB SSD', 'Puerto de 200 Mbit/s', 'Tráfico ilimitado'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps2',
        display_name: 'Cloud VPS 20',
        description: 'Servidor balanceado para APIs, SaaS liviano y cargas sostenidas con más memoria.',
        monthly_price_cents: 882,
        setup_fee_cents: 0,
        cpu_cores: 6,
        ram_mb: 12288,
        disk_mb: 102400,
        storage_type: 'NVMe',
        storage_options: ['100 GB NVMe', '200 GB NVMe', '200 GB SSD', '400 GB SSD'],
        port_speed_mbps: 300,
        bandwidth_label: 'Tráfico ilimitado',
        snapshot_count: 2,
        region: 'EU',
        region_extra_cents: {'EU': 0, 'UK': 145, 'US-EAST': 300, 'US-WEST': 300, 'SIN': 450, 'AUS': 450},
        storage_extra_cents: {'100 GB NVMe': 0, '200 GB NVMe': 255, '200 GB SSD': 0, '400 GB SSD': 195},
        features: ['6 vCPU dedicados', '12 GB RAM', '100 GB NVMe o 200 GB SSD', 'Puerto de 300 Mbit/s', 'Tráfico ilimitado'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps3',
        display_name: 'VPS 30',
        description: 'Nodo dedicado para workloads medianos, workers concurrentes y aplicaciones con tráfico constante.',
        monthly_price_cents: 1764,
        setup_fee_cents: 0,
        cpu_cores: 8,
        ram_mb: 24576,
        disk_mb: 204800,
        storage_type: 'NVMe',
        storage_options: ['200 GB NVMe', '400 GB NVMe', '400 GB SSD', '800 GB SSD'],
        port_speed_mbps: 600,
        bandwidth_label: 'Tráfico ilimitado',
        snapshot_count: 3,
        region: 'EU',
        region_extra_cents: {'EU': 0, 'UK': 295, 'US-EAST': 600, 'US-WEST': 600, 'SIN': 900, 'AUS': 900},
        storage_extra_cents: {'200 GB NVMe': 0, '400 GB NVMe': 325, '400 GB SSD': 0, '800 GB SSD': 385},
        features: ['8 vCPU dedicados', '24 GB RAM', '200 GB NVMe o 400 GB SSD', 'Puerto de 600 Mbit/s', 'Tráfico ilimitado'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps4',
        display_name: 'VPS 40',
        description: 'Capacidad dedicada para pipelines pesados, bases de datos exigentes y servicios con mucha memoria.',
        monthly_price_cents: 3150,
        setup_fee_cents: 0,
        cpu_cores: 12,
        ram_mb: 49152,
        disk_mb: 256000,
        storage_type: 'NVMe',
        storage_options: ['250 GB NVMe', '500 GB NVMe', '500 GB SSD', '1 TB SSD'],
        port_speed_mbps: 800,
        bandwidth_label: 'Tráfico ilimitado',
        snapshot_count: 3,
        region: 'EU',
        region_extra_cents: {'EU': 0, 'UK': 525, 'US-EAST': 1100, 'US-WEST': 1100, 'SIN': 1600, 'AUS': 1600},
        storage_extra_cents: {'250 GB NVMe': 0, '500 GB NVMe': 385, '500 GB SSD': 0, '1 TB SSD': 495},
        features: ['12 vCPU dedicados', '48 GB RAM', '250 GB NVMe o 500 GB SSD', 'Puerto de 800 Mbit/s', 'Tráfico ilimitado'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps5',
        display_name: 'VPS 50',
        description: 'Servidor de alta memoria para cargas intensivas, colas y stacks con varios servicios.',
        monthly_price_cents: 4673,
        setup_fee_cents: 0,
        cpu_cores: 16,
        ram_mb: 65536,
        disk_mb: 307200,
        storage_type: 'NVMe',
        storage_options: ['300 GB NVMe', '600 GB NVMe', '600 GB SSD', '1.2 TB SSD'],
        port_speed_mbps: 1000,
        bandwidth_label: 'Tráfico ilimitado',
        snapshot_count: 3,
        region: 'EU',
        region_extra_cents: {'EU': 0, 'UK': 780, 'US-EAST': 1600, 'US-WEST': 1600, 'SIN': 2400, 'AUS': 2400},
        storage_extra_cents: {'300 GB NVMe': 0, '600 GB NVMe': 475, '600 GB SSD': 0, '1.2 TB SSD': 615},
        features: ['16 vCPU dedicados', '64 GB RAM', '300 GB NVMe o 600 GB SSD', 'Puerto de 1 Gbit/s', 'Tráfico ilimitado'],
        approval_required: true,
        recommended: false,
    },
    {
        tier_name: 'vps6',
        display_name: 'VPS 60',
        description: 'Capacidad máxima del catálogo VPS para workloads pesados y crecimiento sostenido.',
        monthly_price_cents: 6174,
        setup_fee_cents: 0,
        cpu_cores: 18,
        ram_mb: 98304,
        disk_mb: 358400,
        storage_type: 'NVMe',
        storage_options: ['350 GB NVMe', '700 GB NVMe', '700 GB SSD', '1.4 TB SSD'],
        port_speed_mbps: 1000,
        bandwidth_label: 'Tráfico ilimitado',
        snapshot_count: 3,
        region: 'EU',
        region_extra_cents: {'EU': 0, 'UK': 1030, 'US-EAST': 2100, 'US-WEST': 2100, 'SIN': 3200, 'AUS': 3200},
        storage_extra_cents: {'350 GB NVMe': 0, '700 GB NVMe': 575, '700 GB SSD': 0, '1.4 TB SSD': 695},
        features: ['18 vCPU dedicados', '96 GB RAM', '350 GB NVMe o 700 GB SSD', 'Puerto de 1 Gbit/s', 'Tráfico ilimitado'],
        approval_required: true,
        recommended: false,
    },
];

export function useVpsCatalog() {
    const query = useQuery({
        queryKey: ['vps-public-plans'],
        queryFn: apiListPublicVpsPlans,
        staleTime: 5 * 60 * 1000,
    });

    return {
        plans: query.data ?? VPS_PLANS_FALLBACK,
        isLoading: query.isLoading,
        error: query.error,
    };
}