/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Glory Kamples API
 * API Kamples — Rust + Axum + OpenAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-instance';
export interface UserResponse {
  /** @nullable */
  email?: string | null;
  id: number;
  nombre_visible: string;
  plan: string;
  rol: string;
  username: string;
}

export interface AuthResponse {
  refresh_token: string;
  token: string;
  user: UserResponse;
}

export interface BlockUserRequest {
  /** @nullable */
  razon?: string | null;
}

/**
 * Request alternativo: el cliente ya calculó el hash y solo quiere consultar.
 */
export interface CheckDuplicateRequest {
  /** SHA-256 hex precomputado por el cliente (64 chars). */
  audio_hash: string;
}

/**
 * Respuesta de `POST /api/samples/check-duplicate`.
 */
export interface CheckDuplicateResponse {
  /** SHA-256 hex (64 chars) del archivo recibido o del hash precomputado. */
  audio_hash: string;
  /**
     * Bytes leídos durante el cálculo (informativo). 0 si solo se mandó el hash.
     * @minimum 0
     */
  bytes_hashed: number;
  /**
     * Mensaje orientado a UX para el cliente consumidor.
     * @nullable
     */
  message?: string | null;
  /** True si ya existe un sample con ese hash y no está marcado como eliminado. */
  possible_duplicate: boolean;
  /**
     * True si el sample encontrado pertenece al mismo usuario autenticado.
     * @nullable
     */
  same_owner?: boolean | null;
  /**
     * ID del sample existente (solo si `possible_duplicate == true`).
     * @nullable
     */
  sample_id?: number | null;
  /**
     * Título del sample existente, útil para UI/desktop.
     * @nullable
     */
  title?: string | null;
}

export interface DeleteUserRequest {
  /**
     * Dias hasta eliminacion definitiva (default 30).
     * @nullable
     */
  dias_gracia?: number | null;
}

/**
 * Estructura de respuesta de error expuesta en la API
 */
export interface ErrorResponse {
  /** Tipo de error (`not_found`, `unauthorized`, etc.) */
  error: string;
  /** Mensaje legible para el usuario */
  message: string;
}

export interface GoogleAuthRequest {
  id_token: string;
}

export interface GooglePkceRequest {
  /**
     * Opcional: usar uno especifico de los configurados; si se omite, se usa el primero.
     * @nullable
     */
  client_id?: string | null;
  code: string;
  code_verifier: string;
  redirect_uri: string;
}

export interface HealthResponse {
  status: string;
  version: string;
}

export interface LoginRequest {
  identifier: string;
  password: string;
}

export interface LogoutRequest {
  /** @nullable */
  refresh_token?: string | null;
}

/**
 * @nullable
 */
export type PublicProfileResponseGenerosFavoritos = { [key: string]: unknown } | null;

export interface PublicProfileResponse {
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  generos_favoritos?: PublicProfileResponseGenerosFavoritos;
  id: number;
  nombre_visible: string;
  plan: string;
  /** @nullable */
  portada_url?: string | null;
  rol: string;
  /** @nullable */
  sitio_web?: string | null;
  total_descargas: number;
  total_samples: number;
  total_seguidores: number;
  total_seguidos: number;
  username: string;
  verificado: boolean;
}

export type PrivateProfileResponse = PublicProfileResponse & ({
  /** @nullable */
  email?: string | null;
  estado: string;
});

export interface RefreshRequest {
  refresh_token: string;
}

export interface RegisterRequest {
  email: string;
  /** @nullable */
  nombre_visible?: string | null;
  password: string;
  username: string;
}

export interface SuspendUserRequest {
  /**
     * Si se omite, suspension indefinida.
     * @nullable
     */
  hasta?: string | null;
  razon: string;
}

/**
 * @nullable
 */
export type UpdateProfileRequestGenerosFavoritos = { [key: string]: unknown } | null;

export interface UpdateProfileRequest {
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  generos_favoritos?: UpdateProfileRequestGenerosFavoritos;
  /** @nullable */
  nombre_visible?: string | null;
  /** @nullable */
  portada_url?: string | null;
  /** @nullable */
  sitio_web?: string | null;
}

/**
 * Schema documental para `multipart/form-data` en `POST /api/samples/upload`.
 */
export interface UploadSampleRequestDoc {
  audio: Blob;
  /** @nullable */
  contenido?: string | null;
  /** @nullable */
  es_premium?: boolean | null;
  /** @nullable */
  licencia_libre?: boolean | null;
  /** @nullable */
  mostrar_en_comunidad?: boolean | null;
  /** @nullable */
  origen_subida?: string | null;
  /** @nullable */
  permitir_descarga?: boolean | null;
  /** @nullable */
  precio?: number | null;
  /** @nullable */
  sync_upload?: boolean | null;
  /**
     * JSON array (`["tag1","tag2"]`) o CSV (`tag1,tag2`).
     * @nullable
     */
  tags?: string | null;
  /** @nullable */
  titulo?: string | null;
}

/**
 * Respuesta de `POST /api/samples/upload`.
 */
export interface UploadSampleResponse {
  estado: string;
  id_corto: string;
  ok: boolean;
  sample_id: number;
  slug: string;
  url: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type activateResponse204 = {
  data: void
  status: 204
}

export type activateResponse401 = {
  data: void
  status: 401
}

export type activateResponse403 = {
  data: void
  status: 403
}

export type activateResponse404 = {
  data: void
  status: 404
}

export type activateResponseSuccess = (activateResponse204) & {
  headers: Headers;
};
export type activateResponseError = (activateResponse401 | activateResponse403 | activateResponse404) & {
  headers: Headers;
};

export type activateResponse = (activateResponseSuccess | activateResponseError)

export const getActivateUrl = (id: number,) => {




  return `/api/admin/users/${id}/activate`
}

export const activate = async (id: number, options?: RequestInit): Promise<activateResponse> => {

  return customInstance<activateResponse>(getActivateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getActivateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activate>>, TError,{id: number}, TContext> => {

const mutationKey = ['activate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  activate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateMutationResult = NonNullable<Awaited<ReturnType<typeof activate>>>

    export type ActivateMutationError = void

    export const useActivate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activate>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getActivateMutationOptions(options), queryClient);
    }

export type markDeleteResponse204 = {
  data: void
  status: 204
}

export type markDeleteResponse401 = {
  data: void
  status: 401
}

export type markDeleteResponse403 = {
  data: void
  status: 403
}

export type markDeleteResponse404 = {
  data: void
  status: 404
}

export type markDeleteResponseSuccess = (markDeleteResponse204) & {
  headers: Headers;
};
export type markDeleteResponseError = (markDeleteResponse401 | markDeleteResponse403 | markDeleteResponse404) & {
  headers: Headers;
};

export type markDeleteResponse = (markDeleteResponseSuccess | markDeleteResponseError)

export const getMarkDeleteUrl = (id: number,) => {




  return `/api/admin/users/${id}/delete`
}

export const markDelete = async (id: number,
    deleteUserRequest: DeleteUserRequest, options?: RequestInit): Promise<markDeleteResponse> => {

  return customInstance<markDeleteResponse>(getMarkDeleteUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteUserRequest,)
  }
);}




export const getMarkDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markDelete>>, TError,{id: number;data: DeleteUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof markDelete>>, TError,{id: number;data: DeleteUserRequest}, TContext> => {

const mutationKey = ['markDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markDelete>>, {id: number;data: DeleteUserRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  markDelete(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof markDelete>>>
    export type MarkDeleteMutationBody = DeleteUserRequest
    export type MarkDeleteMutationError = void

    export const useMarkDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markDelete>>, TError,{id: number;data: DeleteUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markDelete>>,
        TError,
        {id: number;data: DeleteUserRequest},
        TContext
      > => {
      return useMutation(getMarkDeleteMutationOptions(options), queryClient);
    }

export type suspendResponse204 = {
  data: void
  status: 204
}

export type suspendResponse401 = {
  data: void
  status: 401
}

export type suspendResponse403 = {
  data: void
  status: 403
}

export type suspendResponse404 = {
  data: void
  status: 404
}

export type suspendResponseSuccess = (suspendResponse204) & {
  headers: Headers;
};
export type suspendResponseError = (suspendResponse401 | suspendResponse403 | suspendResponse404) & {
  headers: Headers;
};

export type suspendResponse = (suspendResponseSuccess | suspendResponseError)

export const getSuspendUrl = (id: number,) => {




  return `/api/admin/users/${id}/suspend`
}

export const suspend = async (id: number,
    suspendUserRequest: SuspendUserRequest, options?: RequestInit): Promise<suspendResponse> => {

  return customInstance<suspendResponse>(getSuspendUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      suspendUserRequest,)
  }
);}




export const getSuspendMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suspend>>, TError,{id: number;data: SuspendUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof suspend>>, TError,{id: number;data: SuspendUserRequest}, TContext> => {

const mutationKey = ['suspend'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suspend>>, {id: number;data: SuspendUserRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  suspend(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SuspendMutationResult = NonNullable<Awaited<ReturnType<typeof suspend>>>
    export type SuspendMutationBody = SuspendUserRequest
    export type SuspendMutationError = void

    export const useSuspend = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suspend>>, TError,{id: number;data: SuspendUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suspend>>,
        TError,
        {id: number;data: SuspendUserRequest},
        TContext
      > => {
      return useMutation(getSuspendMutationOptions(options), queryClient);
    }

export type googleLoginResponse200 = {
  data: AuthResponse
  status: 200
}

export type googleLoginResponse401 = {
  data: ErrorResponse
  status: 401
}

export type googleLoginResponse403 = {
  data: ErrorResponse
  status: 403
}

export type googleLoginResponseSuccess = (googleLoginResponse200) & {
  headers: Headers;
};
export type googleLoginResponseError = (googleLoginResponse401 | googleLoginResponse403) & {
  headers: Headers;
};

export type googleLoginResponse = (googleLoginResponseSuccess | googleLoginResponseError)

export const getGoogleLoginUrl = () => {




  return `/api/auth/google`
}

export const googleLogin = async (googleAuthRequest: GoogleAuthRequest, options?: RequestInit): Promise<googleLoginResponse> => {

  return customInstance<googleLoginResponse>(getGoogleLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      googleAuthRequest,)
  }
);}




export const getGoogleLoginMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof googleLogin>>, TError,{data: GoogleAuthRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof googleLogin>>, TError,{data: GoogleAuthRequest}, TContext> => {

const mutationKey = ['googleLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof googleLogin>>, {data: GoogleAuthRequest}> = (props) => {
          const {data} = props ?? {};

          return  googleLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GoogleLoginMutationResult = NonNullable<Awaited<ReturnType<typeof googleLogin>>>
    export type GoogleLoginMutationBody = GoogleAuthRequest
    export type GoogleLoginMutationError = ErrorResponse

    export const useGoogleLogin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof googleLogin>>, TError,{data: GoogleAuthRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof googleLogin>>,
        TError,
        {data: GoogleAuthRequest},
        TContext
      > => {
      return useMutation(getGoogleLoginMutationOptions(options), queryClient);
    }

export type googlePkceResponse200 = {
  data: AuthResponse
  status: 200
}

export type googlePkceResponse401 = {
  data: ErrorResponse
  status: 401
}

export type googlePkceResponse403 = {
  data: ErrorResponse
  status: 403
}

export type googlePkceResponseSuccess = (googlePkceResponse200) & {
  headers: Headers;
};
export type googlePkceResponseError = (googlePkceResponse401 | googlePkceResponse403) & {
  headers: Headers;
};

export type googlePkceResponse = (googlePkceResponseSuccess | googlePkceResponseError)

export const getGooglePkceUrl = () => {




  return `/api/auth/google/pkce`
}

export const googlePkce = async (googlePkceRequest: GooglePkceRequest, options?: RequestInit): Promise<googlePkceResponse> => {

  return customInstance<googlePkceResponse>(getGooglePkceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      googlePkceRequest,)
  }
);}




export const getGooglePkceMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof googlePkce>>, TError,{data: GooglePkceRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof googlePkce>>, TError,{data: GooglePkceRequest}, TContext> => {

const mutationKey = ['googlePkce'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof googlePkce>>, {data: GooglePkceRequest}> = (props) => {
          const {data} = props ?? {};

          return  googlePkce(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GooglePkceMutationResult = NonNullable<Awaited<ReturnType<typeof googlePkce>>>
    export type GooglePkceMutationBody = GooglePkceRequest
    export type GooglePkceMutationError = ErrorResponse

    export const useGooglePkce = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof googlePkce>>, TError,{data: GooglePkceRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof googlePkce>>,
        TError,
        {data: GooglePkceRequest},
        TContext
      > => {
      return useMutation(getGooglePkceMutationOptions(options), queryClient);
    }

export type loginResponse200 = {
  data: AuthResponse
  status: 200
}

export type loginResponse401 = {
  data: ErrorResponse
  status: 401
}

export type loginResponse403 = {
  data: ErrorResponse
  status: 403
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse401 | loginResponse403) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/api/auth/login`
}

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginResponse> => {

  return customInstance<loginResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}




export const getLoginMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = ErrorResponse

    export const useLogin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }

export type logoutResponse204 = {
  data: void
  status: 204
}

export type logoutResponse401 = {
  data: ErrorResponse
  status: 401
}

export type logoutResponseSuccess = (logoutResponse204) & {
  headers: Headers;
};
export type logoutResponseError = (logoutResponse401) & {
  headers: Headers;
};

export type logoutResponse = (logoutResponseSuccess | logoutResponseError)

export const getLogoutUrl = () => {




  return `/api/auth/logout`
}

export const logout = async (logoutRequest: LogoutRequest, options?: RequestInit): Promise<logoutResponse> => {

  return customInstance<logoutResponse>(getLogoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      logoutRequest,)
  }
);}




export const getLogoutMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: LogoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: LogoutRequest}, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, {data: LogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  logout(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    export type LogoutMutationBody = LogoutRequest
    export type LogoutMutationError = ErrorResponse

    export const useLogout = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: LogoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        {data: LogoutRequest},
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options), queryClient);
    }

export type refreshResponse200 = {
  data: AuthResponse
  status: 200
}

export type refreshResponse401 = {
  data: ErrorResponse
  status: 401
}

export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
export type refreshResponseError = (refreshResponse401) & {
  headers: Headers;
};

export type refreshResponse = (refreshResponseSuccess | refreshResponseError)

export const getRefreshUrl = () => {




  return `/api/auth/refresh`
}

export const refresh = async (refreshRequest: RefreshRequest, options?: RequestInit): Promise<refreshResponse> => {

  return customInstance<refreshResponse>(getRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshRequest,)
  }
);}




export const getRefreshMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{data: RefreshRequest}, TContext> => {

const mutationKey = ['refresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refresh>>, {data: RefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  refresh(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshMutationResult = NonNullable<Awaited<ReturnType<typeof refresh>>>
    export type RefreshMutationBody = RefreshRequest
    export type RefreshMutationError = ErrorResponse

    export const useRefresh = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refresh>>,
        TError,
        {data: RefreshRequest},
        TContext
      > => {
      return useMutation(getRefreshMutationOptions(options), queryClient);
    }

export type registerResponse201 = {
  data: AuthResponse
  status: 201
}

export type registerResponse409 = {
  data: ErrorResponse
  status: 409
}

export type registerResponse422 = {
  data: ErrorResponse
  status: 422
}

export type registerResponseSuccess = (registerResponse201) & {
  headers: Headers;
};
export type registerResponseError = (registerResponse409 | registerResponse422) & {
  headers: Headers;
};

export type registerResponse = (registerResponseSuccess | registerResponseError)

export const getRegisterUrl = () => {




  return `/api/auth/register`
}

export const register = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<registerResponse> => {

  return customInstance<registerResponse>(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}




export const getRegisterMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterRequest
    export type RegisterMutationError = ErrorResponse

    export const useRegister = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options), queryClient);
    }

/**
 * @summary Endpoint de health check — siempre público
 */
export type healthCheckResponse200 = {
  data: HealthResponse
  status: 200
}

export type healthCheckResponseSuccess = (healthCheckResponse200) & {
  headers: Headers;
};
;

export type healthCheckResponse = (healthCheckResponseSuccess)

export const getHealthCheckUrl = () => {




  return `/api/health`
}

export const healthCheck = async ( options?: RequestInit): Promise<healthCheckResponse> => {

  return customInstance<healthCheckResponse>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = unknown


export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Endpoint de health check — siempre público
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type checkDuplicateResponse200 = {
  data: CheckDuplicateResponse
  status: 200
}

export type checkDuplicateResponse400 = {
  data: ErrorResponse
  status: 400
}

export type checkDuplicateResponse401 = {
  data: ErrorResponse
  status: 401
}

export type checkDuplicateResponse413 = {
  data: ErrorResponse
  status: 413
}

export type checkDuplicateResponseSuccess = (checkDuplicateResponse200) & {
  headers: Headers;
};
export type checkDuplicateResponseError = (checkDuplicateResponse400 | checkDuplicateResponse401 | checkDuplicateResponse413) & {
  headers: Headers;
};

export type checkDuplicateResponse = (checkDuplicateResponseSuccess | checkDuplicateResponseError)

export const getCheckDuplicateUrl = () => {




  return `/api/samples/check-duplicate`
}

export const checkDuplicate = async (checkDuplicateRequest: CheckDuplicateRequest, options?: RequestInit): Promise<checkDuplicateResponse> => {

  return customInstance<checkDuplicateResponse>(getCheckDuplicateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      checkDuplicateRequest,)
  }
);}




export const getCheckDuplicateMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkDuplicate>>, TError,{data: CheckDuplicateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof checkDuplicate>>, TError,{data: CheckDuplicateRequest}, TContext> => {

const mutationKey = ['checkDuplicate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkDuplicate>>, {data: CheckDuplicateRequest}> = (props) => {
          const {data} = props ?? {};

          return  checkDuplicate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckDuplicateMutationResult = NonNullable<Awaited<ReturnType<typeof checkDuplicate>>>
    export type CheckDuplicateMutationBody = CheckDuplicateRequest
    export type CheckDuplicateMutationError = ErrorResponse

    export const useCheckDuplicate = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkDuplicate>>, TError,{data: CheckDuplicateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkDuplicate>>,
        TError,
        {data: CheckDuplicateRequest},
        TContext
      > => {
      return useMutation(getCheckDuplicateMutationOptions(options), queryClient);
    }

export type uploadResponse200 = {
  data: UploadSampleResponse
  status: 200
}

export type uploadResponse201 = {
  data: UploadSampleResponse
  status: 201
}

export type uploadResponse400 = {
  data: ErrorResponse
  status: 400
}

export type uploadResponse401 = {
  data: ErrorResponse
  status: 401
}

export type uploadResponse403 = {
  data: ErrorResponse
  status: 403
}

export type uploadResponse413 = {
  data: ErrorResponse
  status: 413
}

export type uploadResponseSuccess = (uploadResponse200 | uploadResponse201) & {
  headers: Headers;
};
export type uploadResponseError = (uploadResponse400 | uploadResponse401 | uploadResponse403 | uploadResponse413) & {
  headers: Headers;
};

export type uploadResponse = (uploadResponseSuccess | uploadResponseError)

export const getUploadUrl = () => {




  return `/api/samples/upload`
}

export const upload = async (uploadSampleRequestDoc: UploadSampleRequestDoc, options?: RequestInit): Promise<uploadResponse> => {
    const formData = new FormData();
formData.append(`audio`, uploadSampleRequestDoc.audio);
if(uploadSampleRequestDoc.contenido !== undefined && uploadSampleRequestDoc.contenido !== null) {
 formData.append(`contenido`, uploadSampleRequestDoc.contenido);
 }
if(uploadSampleRequestDoc.es_premium !== undefined && uploadSampleRequestDoc.es_premium !== null) {
 formData.append(`es_premium`, uploadSampleRequestDoc.es_premium.toString())
 }
if(uploadSampleRequestDoc.licencia_libre !== undefined && uploadSampleRequestDoc.licencia_libre !== null) {
 formData.append(`licencia_libre`, uploadSampleRequestDoc.licencia_libre.toString())
 }
if(uploadSampleRequestDoc.mostrar_en_comunidad !== undefined && uploadSampleRequestDoc.mostrar_en_comunidad !== null) {
 formData.append(`mostrar_en_comunidad`, uploadSampleRequestDoc.mostrar_en_comunidad.toString())
 }
if(uploadSampleRequestDoc.origen_subida !== undefined && uploadSampleRequestDoc.origen_subida !== null) {
 formData.append(`origen_subida`, uploadSampleRequestDoc.origen_subida);
 }
if(uploadSampleRequestDoc.permitir_descarga !== undefined && uploadSampleRequestDoc.permitir_descarga !== null) {
 formData.append(`permitir_descarga`, uploadSampleRequestDoc.permitir_descarga.toString())
 }
if(uploadSampleRequestDoc.precio !== undefined && uploadSampleRequestDoc.precio !== null) {
 formData.append(`precio`, uploadSampleRequestDoc.precio.toString())
 }
if(uploadSampleRequestDoc.sync_upload !== undefined && uploadSampleRequestDoc.sync_upload !== null) {
 formData.append(`sync_upload`, uploadSampleRequestDoc.sync_upload.toString())
 }
if(uploadSampleRequestDoc.tags !== undefined && uploadSampleRequestDoc.tags !== null) {
 formData.append(`tags`, uploadSampleRequestDoc.tags);
 }
if(uploadSampleRequestDoc.titulo !== undefined && uploadSampleRequestDoc.titulo !== null) {
 formData.append(`titulo`, uploadSampleRequestDoc.titulo);
 }

  return customInstance<uploadResponse>(getUploadUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getUploadMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{data: UploadSampleRequestDoc}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{data: UploadSampleRequestDoc}, TContext> => {

const mutationKey = ['upload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upload>>, {data: UploadSampleRequestDoc}> = (props) => {
          const {data} = props ?? {};

          return  upload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadMutationResult = NonNullable<Awaited<ReturnType<typeof upload>>>
    export type UploadMutationBody = UploadSampleRequestDoc
    export type UploadMutationError = ErrorResponse

    export const useUpload = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{data: UploadSampleRequestDoc}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upload>>,
        TError,
        {data: UploadSampleRequestDoc},
        TContext
      > => {
      return useMutation(getUploadMutationOptions(options), queryClient);
    }

export type meResponse200 = {
  data: PrivateProfileResponse
  status: 200
}

export type meResponse401 = {
  data: ErrorResponse
  status: 401
}

export type meResponseSuccess = (meResponse200) & {
  headers: Headers;
};
export type meResponseError = (meResponse401) & {
  headers: Headers;
};

export type meResponse = (meResponseSuccess | meResponseError)

export const getMeUrl = () => {




  return `/api/users/me`
}

export const me = async ( options?: RequestInit): Promise<meResponse> => {

  return customInstance<meResponse>(getMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getMeQueryKey = () => {
    return [
    `/api/users/me`
    ] as const;
    }


export const getMeQueryOptions = <TData = Awaited<ReturnType<typeof me>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({ signal }) => me({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>
export type MeQueryError = ErrorResponse


export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type updateMeResponse200 = {
  data: PrivateProfileResponse
  status: 200
}

export type updateMeResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateMeResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateMeResponseSuccess = (updateMeResponse200) & {
  headers: Headers;
};
export type updateMeResponseError = (updateMeResponse401 | updateMeResponse422) & {
  headers: Headers;
};

export type updateMeResponse = (updateMeResponseSuccess | updateMeResponseError)

export const getUpdateMeUrl = () => {




  return `/api/users/me`
}

export const updateMe = async (updateProfileRequest: UpdateProfileRequest, options?: RequestInit): Promise<updateMeResponse> => {

  return customInstance<updateMeResponse>(getUpdateMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileRequest,)
  }
);}




export const getUpdateMeMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: UpdateProfileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: UpdateProfileRequest}, TContext> => {

const mutationKey = ['updateMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMe>>, {data: UpdateProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateMe(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeMutationResult = NonNullable<Awaited<ReturnType<typeof updateMe>>>
    export type UpdateMeMutationBody = UpdateProfileRequest
    export type UpdateMeMutationError = ErrorResponse

    export const useUpdateMe = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: UpdateProfileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMe>>,
        TError,
        {data: UpdateProfileRequest},
        TContext
      > => {
      return useMutation(getUpdateMeMutationOptions(options), queryClient);
    }

export type listBlockedResponse200 = {
  data: number[]
  status: 200
}

export type listBlockedResponse401 = {
  data: void
  status: 401
}

export type listBlockedResponseSuccess = (listBlockedResponse200) & {
  headers: Headers;
};
export type listBlockedResponseError = (listBlockedResponse401) & {
  headers: Headers;
};

export type listBlockedResponse = (listBlockedResponseSuccess | listBlockedResponseError)

export const getListBlockedUrl = () => {




  return `/api/users/me/blocked`
}

export const listBlocked = async ( options?: RequestInit): Promise<listBlockedResponse> => {

  return customInstance<listBlockedResponse>(getListBlockedUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListBlockedQueryKey = () => {
    return [
    `/api/users/me/blocked`
    ] as const;
    }


export const getListBlockedQueryOptions = <TData = Awaited<ReturnType<typeof listBlocked>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBlocked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBlockedQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBlocked>>> = ({ signal }) => listBlocked({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBlocked>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBlockedQueryResult = NonNullable<Awaited<ReturnType<typeof listBlocked>>>
export type ListBlockedQueryError = void


export function useListBlocked<TData = Awaited<ReturnType<typeof listBlocked>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBlocked>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBlocked>>,
          TError,
          Awaited<ReturnType<typeof listBlocked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBlocked<TData = Awaited<ReturnType<typeof listBlocked>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBlocked>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBlocked>>,
          TError,
          Awaited<ReturnType<typeof listBlocked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBlocked<TData = Awaited<ReturnType<typeof listBlocked>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBlocked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListBlocked<TData = Awaited<ReturnType<typeof listBlocked>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBlocked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListBlockedQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type publicProfileResponse200 = {
  data: PublicProfileResponse
  status: 200
}

export type publicProfileResponse404 = {
  data: ErrorResponse
  status: 404
}

export type publicProfileResponseSuccess = (publicProfileResponse200) & {
  headers: Headers;
};
export type publicProfileResponseError = (publicProfileResponse404) & {
  headers: Headers;
};

export type publicProfileResponse = (publicProfileResponseSuccess | publicProfileResponseError)

export const getPublicProfileUrl = (username: string,) => {




  return `/api/users/${username}`
}

export const publicProfile = async (username: string, options?: RequestInit): Promise<publicProfileResponse> => {

  return customInstance<publicProfileResponse>(getPublicProfileUrl(username),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPublicProfileQueryKey = (username: string,) => {
    return [
    `/api/users/${username}`
    ] as const;
    }


export const getPublicProfileQueryOptions = <TData = Awaited<ReturnType<typeof publicProfile>>, TError = ErrorResponse>(username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicProfileQueryKey(username);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicProfile>>> = ({ signal }) => publicProfile(username, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicProfileQueryResult = NonNullable<Awaited<ReturnType<typeof publicProfile>>>
export type PublicProfileQueryError = ErrorResponse


export function usePublicProfile<TData = Awaited<ReturnType<typeof publicProfile>>, TError = ErrorResponse>(
 username: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicProfile>>,
          TError,
          Awaited<ReturnType<typeof publicProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicProfile<TData = Awaited<ReturnType<typeof publicProfile>>, TError = ErrorResponse>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicProfile>>,
          TError,
          Awaited<ReturnType<typeof publicProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicProfile<TData = Awaited<ReturnType<typeof publicProfile>>, TError = ErrorResponse>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePublicProfile<TData = Awaited<ReturnType<typeof publicProfile>>, TError = ErrorResponse>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicProfileQueryOptions(username,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type blockResponse204 = {
  data: void
  status: 204
}

export type blockResponse400 = {
  data: void
  status: 400
}

export type blockResponse401 = {
  data: void
  status: 401
}

export type blockResponse404 = {
  data: void
  status: 404
}

export type blockResponseSuccess = (blockResponse204) & {
  headers: Headers;
};
export type blockResponseError = (blockResponse400 | blockResponse401 | blockResponse404) & {
  headers: Headers;
};

export type blockResponse = (blockResponseSuccess | blockResponseError)

export const getBlockUrl = (username: string,) => {




  return `/api/users/${username}/block`
}

export const block = async (username: string,
    blockUserRequest: BlockUserRequest, options?: RequestInit): Promise<blockResponse> => {

  return customInstance<blockResponse>(getBlockUrl(username),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      blockUserRequest,)
  }
);}




export const getBlockMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof block>>, TError,{username: string;data: BlockUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof block>>, TError,{username: string;data: BlockUserRequest}, TContext> => {

const mutationKey = ['block'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof block>>, {username: string;data: BlockUserRequest}> = (props) => {
          const {username,data} = props ?? {};

          return  block(username,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlockMutationResult = NonNullable<Awaited<ReturnType<typeof block>>>
    export type BlockMutationBody = BlockUserRequest
    export type BlockMutationError = void

    export const useBlock = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof block>>, TError,{username: string;data: BlockUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof block>>,
        TError,
        {username: string;data: BlockUserRequest},
        TContext
      > => {
      return useMutation(getBlockMutationOptions(options), queryClient);
    }

export type unblockResponse204 = {
  data: void
  status: 204
}

export type unblockResponse401 = {
  data: void
  status: 401
}

export type unblockResponse404 = {
  data: void
  status: 404
}

export type unblockResponseSuccess = (unblockResponse204) & {
  headers: Headers;
};
export type unblockResponseError = (unblockResponse401 | unblockResponse404) & {
  headers: Headers;
};

export type unblockResponse = (unblockResponseSuccess | unblockResponseError)

export const getUnblockUrl = (username: string,) => {




  return `/api/users/${username}/block`
}

export const unblock = async (username: string, options?: RequestInit): Promise<unblockResponse> => {

  return customInstance<unblockResponse>(getUnblockUrl(username),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getUnblockMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblock>>, TError,{username: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof unblock>>, TError,{username: string}, TContext> => {

const mutationKey = ['unblock'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unblock>>, {username: string}> = (props) => {
          const {username} = props ?? {};

          return  unblock(username,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnblockMutationResult = NonNullable<Awaited<ReturnType<typeof unblock>>>

    export type UnblockMutationError = void

    export const useUnblock = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblock>>, TError,{username: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unblock>>,
        TError,
        {username: string},
        TContext
      > => {
      return useMutation(getUnblockMutationOptions(options), queryClient);
    }
