/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Gestión Restaurante API
 * API para gestión de restaurantes — Ventas, Gastos, Reservas, Dashboard
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-instance';
/**
 * Estados posibles de una reserva
 */
export type EstadoReserva = typeof EstadoReserva[keyof typeof EstadoReserva];


export const EstadoReserva = {
  pendiente: 'pendiente',
  confirmada: 'confirmada',
  cancelada: 'cancelada',
  completada: 'completada',
} as const;

/**
 * Request para actualizar una reserva
 */
export interface ActualizarReservaRequest {
  estado?: EstadoReserva | null;
  /** @nullable */
  fecha?: string | null;
  /** @nullable */
  hora?: string | null;
  /** @nullable */
  nombre_cliente?: string | null;
  /** @nullable */
  notas?: string | null;
  /** @nullable */
  num_personas?: number | null;
  /** @nullable */
  telefono?: string | null;
}

/**
 * Response con token JWT después de autenticarse
 */
export interface AuthResponse {
  token: string;
  user_id: string;
}

/**
 * Canales de venta disponibles
 */
export type CanalVenta = typeof CanalVenta[keyof typeof CanalVenta];


export const CanalVenta = {
  comedor: 'comedor',
  barra: 'barra',
  terraza: 'terraza',
  delivery: 'delivery',
  just_eat: 'just_eat',
  eventos: 'eventos',
} as const;

/**
 * Categoría de gasto — precargada en BD
 */
export interface CategoriaGasto {
  color: string;
  created_at: string;
  id: string;
  nombre: string;
}

/**
 * Métodos de pago soportados — compartido entre ventas y gastos
 */
export type MetodoPago = typeof MetodoPago[keyof typeof MetodoPago];


export const MetodoPago = {
  efectivo: 'efectivo',
  tarjeta: 'tarjeta',
  transferencia: 'transferencia',
} as const;

/**
 * Tipos de documento de gasto
 */
export type TipoDocumento = typeof TipoDocumento[keyof typeof TipoDocumento];


export const TipoDocumento = {
  factura: 'factura',
  albaran: 'albaran',
  ticket: 'ticket',
} as const;

/**
 * Request para crear un gasto
 */
export interface CrearGastoRequest {
  /** @nullable */
  categoria_id?: string | null;
  fecha: string;
  importe_base: string;
  importe_iva: string;
  metodo_pago: MetodoPago;
  /** @nullable */
  numero_documento?: string | null;
  /** @nullable */
  proveedor?: string | null;
  /** @nullable */
  recurrente?: boolean | null;
  tipo_documento: TipoDocumento;
}

/**
 * Request para crear una reserva
 */
export interface CrearReservaRequest {
  estado?: EstadoReserva | null;
  fecha: string;
  hora: string;
  nombre_cliente: string;
  /** @nullable */
  notas?: string | null;
  num_personas: number;
  /** @nullable */
  telefono?: string | null;
}

/**
 * Turnos de servicio del restaurante
 */
export type Turno = typeof Turno[keyof typeof Turno];


export const Turno = {
  manana: 'manana',
  mediodia: 'mediodia',
  noche: 'noche',
} as const;

/**
 * Request para crear una venta
 */
export interface CrearVentaRequest {
  canal: CanalVenta;
  /** @nullable */
  comensales?: number | null;
  /** @nullable */
  descripcion?: string | null;
  fecha: string;
  importe_base: string;
  importe_iva: string;
  iva_porcentaje: string;
  metodo_pago: MetodoPago;
  turno: Turno;
}

/**
 * Estructura de respuesta de error expuesta en la API
 */
export interface ErrorResponse {
  /** Tipo de error (`not_found`, `unauthorized`, etc.) */
  error: string;
  /** Mensaje legible para el usuario */
  message: string;
}

/**
 * Gasto registrado en el restaurante
 */
export interface Gasto {
  /** @nullable */
  categoria_id?: string | null;
  created_at: string;
  fecha: string;
  id: string;
  importe_base: string;
  importe_iva: string;
  metodo_pago: string;
  numero_documento: string;
  proveedor: string;
  recurrente: boolean;
  tipo_documento: string;
  updated_at: string;
  user_id: string;
}

/**
 * Response paginada de gastos
 */
export interface GastosPaginados {
  items: Gasto[];
  page: number;
  per_page: number;
  total: number;
}

export interface HealthResponse {
  status: string;
  version: string;
}

/**
 * Request body para iniciar sesión
 */
export interface LoginRequest {
  email: string;
  password: string;
}

/**
 * Request body para registrar un nuevo usuario
 */
export interface RegisterRequest {
  email: string;
  password: string;
}

/**
 * Reserva del restaurante
 */
export interface Reserva {
  created_at: string;
  estado: string;
  fecha: string;
  hora: string;
  id: string;
  nombre_cliente: string;
  notas: string;
  num_personas: number;
  telefono: string;
  updated_at: string;
  user_id: string;
}

/**
 * Conteo de reservas para el Home — mes y día actual
 */
export interface ReservasConteo {
  total_hoy: number;
  total_mes: number;
}

/**
 * Response paginada de reservas
 */
export interface ReservasPaginadas {
  items: Reserva[];
  page: number;
  per_page: number;
  total: number;
}

/**
 * Resumen económico: Gastos totales, Ventas totales, Margen
 */
export interface ResumenEconomico {
  /** Margen = ventas - gastos. Negativo si hay pérdidas */
  margen: string;
  mes: string;
  total_gastos: string;
  total_ventas: string;
}

/**
 * Venta registrada en el restaurante
 */
export interface Venta {
  canal: string;
  /** @nullable */
  comensales?: number | null;
  created_at: string;
  descripcion: string;
  fecha: string;
  id: string;
  importe_base: string;
  importe_iva: string;
  iva_porcentaje: string;
  metodo_pago: string;
  turno: string;
  updated_at: string;
  user_id: string;
}

/**
 * Response paginada de ventas
 */
export interface VentasPaginadas {
  items: Venta[];
  page: number;
  per_page: number;
  total: number;
}

export type ResumenParams = {
/**
 * Año (ej: 2026)
 */
year: number;
/**
 * Mes (1-12)
 * @minimum 0
 */
month: number;
};

export type ListarGastosParams = {
page?: number;
per_page?: number;
/**
 * @nullable
 */
desde?: string | null;
/**
 * @nullable
 */
hasta?: string | null;
/**
 * @nullable
 */
categoria_id?: string | null;
};

export type ListarReservasParams = {
page?: number;
per_page?: number;
/**
 * @nullable
 */
fecha?: string | null;
};

export type ListarVentasParams = {
page?: number;
per_page?: number;
/**
 * Filtrar desde esta fecha (YYYY-MM-DD)
 * @nullable
 */
desde?: string | null;
/**
 * Filtrar hasta esta fecha (YYYY-MM-DD)
 * @nullable
 */
hasta?: string | null;
};

/**
 * @summary Iniciar sesión
 */
export type loginResponse200 = {
  data: AuthResponse
  status: 200
}

export type loginResponse401 = {
  data: ErrorResponse
  status: 401
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse401) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/api/auth/login`
}

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginResponse> => {

  return customInstance<loginResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}




export const getLoginMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = ErrorResponse

    /**
 * @summary Iniciar sesión
 */
export const useLogin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }

/**
 * @summary Registrar nuevo usuario
 */
export type registerResponse201 = {
  data: AuthResponse
  status: 201
}

export type registerResponse409 = {
  data: ErrorResponse
  status: 409
}

export type registerResponse422 = {
  data: ErrorResponse
  status: 422
}

export type registerResponseSuccess = (registerResponse201) & {
  headers: Headers;
};
export type registerResponseError = (registerResponse409 | registerResponse422) & {
  headers: Headers;
};

export type registerResponse = (registerResponseSuccess | registerResponseError)

export const getRegisterUrl = () => {




  return `/api/auth/register`
}

export const register = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<registerResponse> => {

  return customInstance<registerResponse>(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}




export const getRegisterMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  register(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterRequest
    export type RegisterMutationError = ErrorResponse

    /**
 * @summary Registrar nuevo usuario
 */
export const useRegister = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options), queryClient);
    }

/**
 * @summary Resumen económico mensual: ventas, gastos, margen
 */
export type resumenResponse200 = {
  data: ResumenEconomico
  status: 200
}

export type resumenResponse401 = {
  data: ErrorResponse
  status: 401
}

export type resumenResponseSuccess = (resumenResponse200) & {
  headers: Headers;
};
export type resumenResponseError = (resumenResponse401) & {
  headers: Headers;
};

export type resumenResponse = (resumenResponseSuccess | resumenResponseError)

export const getResumenUrl = (params: ResumenParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/resumen?${stringifiedParams}` : `/api/dashboard/resumen`
}

export const resumen = async (params: ResumenParams, options?: RequestInit): Promise<resumenResponse> => {

  return customInstance<resumenResponse>(getResumenUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getResumenQueryKey = (params?: ResumenParams,) => {
    return [
    `/api/dashboard/resumen`, ...(params ? [params] : [])
    ] as const;
    }


export const getResumenQueryOptions = <TData = Awaited<ReturnType<typeof resumen>>, TError = ErrorResponse>(params: ResumenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumen>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResumenQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof resumen>>> = ({ signal }) => resumen(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resumen>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResumenQueryResult = NonNullable<Awaited<ReturnType<typeof resumen>>>
export type ResumenQueryError = ErrorResponse


export function useResumen<TData = Awaited<ReturnType<typeof resumen>>, TError = ErrorResponse>(
 params: ResumenParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumen>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resumen>>,
          TError,
          Awaited<ReturnType<typeof resumen>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResumen<TData = Awaited<ReturnType<typeof resumen>>, TError = ErrorResponse>(
 params: ResumenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumen>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resumen>>,
          TError,
          Awaited<ReturnType<typeof resumen>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResumen<TData = Awaited<ReturnType<typeof resumen>>, TError = ErrorResponse>(
 params: ResumenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumen>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resumen económico mensual: ventas, gastos, margen
 */

export function useResumen<TData = Awaited<ReturnType<typeof resumen>>, TError = ErrorResponse>(
 params: ResumenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumen>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResumenQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Listar gastos con paginación y filtros
 */
export type listarGastosResponse200 = {
  data: GastosPaginados
  status: 200
}

export type listarGastosResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listarGastosResponseSuccess = (listarGastosResponse200) & {
  headers: Headers;
};
export type listarGastosResponseError = (listarGastosResponse401) & {
  headers: Headers;
};

export type listarGastosResponse = (listarGastosResponseSuccess | listarGastosResponseError)

export const getListarGastosUrl = (params?: ListarGastosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/gastos?${stringifiedParams}` : `/api/gastos`
}

export const listarGastos = async (params?: ListarGastosParams, options?: RequestInit): Promise<listarGastosResponse> => {

  return customInstance<listarGastosResponse>(getListarGastosUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarGastosQueryKey = (params?: ListarGastosParams,) => {
    return [
    `/api/gastos`, ...(params ? [params] : [])
    ] as const;
    }


export const getListarGastosQueryOptions = <TData = Awaited<ReturnType<typeof listarGastos>>, TError = ErrorResponse>(params?: ListarGastosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarGastos>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarGastosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarGastos>>> = ({ signal }) => listarGastos(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarGastos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarGastosQueryResult = NonNullable<Awaited<ReturnType<typeof listarGastos>>>
export type ListarGastosQueryError = ErrorResponse


export function useListarGastos<TData = Awaited<ReturnType<typeof listarGastos>>, TError = ErrorResponse>(
 params: undefined |  ListarGastosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarGastos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarGastos>>,
          TError,
          Awaited<ReturnType<typeof listarGastos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarGastos<TData = Awaited<ReturnType<typeof listarGastos>>, TError = ErrorResponse>(
 params?: ListarGastosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarGastos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarGastos>>,
          TError,
          Awaited<ReturnType<typeof listarGastos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarGastos<TData = Awaited<ReturnType<typeof listarGastos>>, TError = ErrorResponse>(
 params?: ListarGastosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarGastos>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar gastos con paginación y filtros
 */

export function useListarGastos<TData = Awaited<ReturnType<typeof listarGastos>>, TError = ErrorResponse>(
 params?: ListarGastosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarGastos>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarGastosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Crear un gasto
 */
export type crearGastoResponse201 = {
  data: Gasto
  status: 201
}

export type crearGastoResponse401 = {
  data: ErrorResponse
  status: 401
}

export type crearGastoResponse422 = {
  data: ErrorResponse
  status: 422
}

export type crearGastoResponseSuccess = (crearGastoResponse201) & {
  headers: Headers;
};
export type crearGastoResponseError = (crearGastoResponse401 | crearGastoResponse422) & {
  headers: Headers;
};

export type crearGastoResponse = (crearGastoResponseSuccess | crearGastoResponseError)

export const getCrearGastoUrl = () => {




  return `/api/gastos`
}

export const crearGasto = async (crearGastoRequest: CrearGastoRequest, options?: RequestInit): Promise<crearGastoResponse> => {

  return customInstance<crearGastoResponse>(getCrearGastoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      crearGastoRequest,)
  }
);}




export const getCrearGastoMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof crearGasto>>, TError,{data: CrearGastoRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof crearGasto>>, TError,{data: CrearGastoRequest}, TContext> => {

const mutationKey = ['crearGasto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof crearGasto>>, {data: CrearGastoRequest}> = (props) => {
          const {data} = props ?? {};

          return  crearGasto(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CrearGastoMutationResult = NonNullable<Awaited<ReturnType<typeof crearGasto>>>
    export type CrearGastoMutationBody = CrearGastoRequest
    export type CrearGastoMutationError = ErrorResponse

    /**
 * @summary Crear un gasto
 */
export const useCrearGasto = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof crearGasto>>, TError,{data: CrearGastoRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof crearGasto>>,
        TError,
        {data: CrearGastoRequest},
        TContext
      > => {
      return useMutation(getCrearGastoMutationOptions(options), queryClient);
    }

/**
 * @summary Listar categorías de gasto — endpoint público
 */
export type listarCategoriasResponse200 = {
  data: CategoriaGasto[]
  status: 200
}

export type listarCategoriasResponseSuccess = (listarCategoriasResponse200) & {
  headers: Headers;
};
;

export type listarCategoriasResponse = (listarCategoriasResponseSuccess)

export const getListarCategoriasUrl = () => {




  return `/api/gastos/categorias`
}

export const listarCategorias = async ( options?: RequestInit): Promise<listarCategoriasResponse> => {

  return customInstance<listarCategoriasResponse>(getListarCategoriasUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarCategoriasQueryKey = () => {
    return [
    `/api/gastos/categorias`
    ] as const;
    }


export const getListarCategoriasQueryOptions = <TData = Awaited<ReturnType<typeof listarCategorias>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarCategoriasQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarCategorias>>> = ({ signal }) => listarCategorias({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarCategoriasQueryResult = NonNullable<Awaited<ReturnType<typeof listarCategorias>>>
export type ListarCategoriasQueryError = unknown


export function useListarCategorias<TData = Awaited<ReturnType<typeof listarCategorias>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarCategorias>>,
          TError,
          Awaited<ReturnType<typeof listarCategorias>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarCategorias<TData = Awaited<ReturnType<typeof listarCategorias>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarCategorias>>,
          TError,
          Awaited<ReturnType<typeof listarCategorias>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarCategorias<TData = Awaited<ReturnType<typeof listarCategorias>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar categorías de gasto — endpoint público
 */

export function useListarCategorias<TData = Awaited<ReturnType<typeof listarCategorias>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarCategoriasQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Obtener un gasto por ID
 */
export type obtenerGastoResponse200 = {
  data: Gasto
  status: 200
}

export type obtenerGastoResponse401 = {
  data: ErrorResponse
  status: 401
}

export type obtenerGastoResponse404 = {
  data: ErrorResponse
  status: 404
}

export type obtenerGastoResponseSuccess = (obtenerGastoResponse200) & {
  headers: Headers;
};
export type obtenerGastoResponseError = (obtenerGastoResponse401 | obtenerGastoResponse404) & {
  headers: Headers;
};

export type obtenerGastoResponse = (obtenerGastoResponseSuccess | obtenerGastoResponseError)

export const getObtenerGastoUrl = (id: string,) => {




  return `/api/gastos/${id}`
}

export const obtenerGasto = async (id: string, options?: RequestInit): Promise<obtenerGastoResponse> => {

  return customInstance<obtenerGastoResponse>(getObtenerGastoUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerGastoQueryKey = (id: string,) => {
    return [
    `/api/gastos/${id}`
    ] as const;
    }


export const getObtenerGastoQueryOptions = <TData = Awaited<ReturnType<typeof obtenerGasto>>, TError = ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerGasto>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerGastoQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerGasto>>> = ({ signal }) => obtenerGasto(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerGasto>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerGastoQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerGasto>>>
export type ObtenerGastoQueryError = ErrorResponse


export function useObtenerGasto<TData = Awaited<ReturnType<typeof obtenerGasto>>, TError = ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerGasto>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerGasto>>,
          TError,
          Awaited<ReturnType<typeof obtenerGasto>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerGasto<TData = Awaited<ReturnType<typeof obtenerGasto>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerGasto>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerGasto>>,
          TError,
          Awaited<ReturnType<typeof obtenerGasto>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerGasto<TData = Awaited<ReturnType<typeof obtenerGasto>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerGasto>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener un gasto por ID
 */

export function useObtenerGasto<TData = Awaited<ReturnType<typeof obtenerGasto>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerGasto>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerGastoQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Eliminar un gasto
 */
export type eliminarGastoResponse204 = {
  data: void
  status: 204
}

export type eliminarGastoResponse401 = {
  data: ErrorResponse
  status: 401
}

export type eliminarGastoResponse404 = {
  data: ErrorResponse
  status: 404
}

export type eliminarGastoResponseSuccess = (eliminarGastoResponse204) & {
  headers: Headers;
};
export type eliminarGastoResponseError = (eliminarGastoResponse401 | eliminarGastoResponse404) & {
  headers: Headers;
};

export type eliminarGastoResponse = (eliminarGastoResponseSuccess | eliminarGastoResponseError)

export const getEliminarGastoUrl = (id: string,) => {




  return `/api/gastos/${id}`
}

export const eliminarGasto = async (id: string, options?: RequestInit): Promise<eliminarGastoResponse> => {

  return customInstance<eliminarGastoResponse>(getEliminarGastoUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEliminarGastoMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eliminarGasto>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof eliminarGasto>>, TError,{id: string}, TContext> => {

const mutationKey = ['eliminarGasto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eliminarGasto>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  eliminarGasto(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EliminarGastoMutationResult = NonNullable<Awaited<ReturnType<typeof eliminarGasto>>>

    export type EliminarGastoMutationError = ErrorResponse

    /**
 * @summary Eliminar un gasto
 */
export const useEliminarGasto = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eliminarGasto>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eliminarGasto>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getEliminarGastoMutationOptions(options), queryClient);
    }

/**
 * @summary Endpoint de health check — siempre público
 */
export type healthCheckResponse200 = {
  data: HealthResponse
  status: 200
}

export type healthCheckResponseSuccess = (healthCheckResponse200) & {
  headers: Headers;
};
;

export type healthCheckResponse = (healthCheckResponseSuccess)

export const getHealthCheckUrl = () => {




  return `/api/health`
}

export const healthCheck = async ( options?: RequestInit): Promise<healthCheckResponse> => {

  return customInstance<healthCheckResponse>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = unknown


export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Endpoint de health check — siempre público
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Listar reservas con paginación y filtro por fecha
 */
export type listarReservasResponse200 = {
  data: ReservasPaginadas
  status: 200
}

export type listarReservasResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listarReservasResponseSuccess = (listarReservasResponse200) & {
  headers: Headers;
};
export type listarReservasResponseError = (listarReservasResponse401) & {
  headers: Headers;
};

export type listarReservasResponse = (listarReservasResponseSuccess | listarReservasResponseError)

export const getListarReservasUrl = (params?: ListarReservasParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reservas?${stringifiedParams}` : `/api/reservas`
}

export const listarReservas = async (params?: ListarReservasParams, options?: RequestInit): Promise<listarReservasResponse> => {

  return customInstance<listarReservasResponse>(getListarReservasUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarReservasQueryKey = (params?: ListarReservasParams,) => {
    return [
    `/api/reservas`, ...(params ? [params] : [])
    ] as const;
    }


export const getListarReservasQueryOptions = <TData = Awaited<ReturnType<typeof listarReservas>>, TError = ErrorResponse>(params?: ListarReservasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReservas>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarReservasQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarReservas>>> = ({ signal }) => listarReservas(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarReservas>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarReservasQueryResult = NonNullable<Awaited<ReturnType<typeof listarReservas>>>
export type ListarReservasQueryError = ErrorResponse


export function useListarReservas<TData = Awaited<ReturnType<typeof listarReservas>>, TError = ErrorResponse>(
 params: undefined |  ListarReservasParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReservas>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarReservas>>,
          TError,
          Awaited<ReturnType<typeof listarReservas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarReservas<TData = Awaited<ReturnType<typeof listarReservas>>, TError = ErrorResponse>(
 params?: ListarReservasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReservas>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarReservas>>,
          TError,
          Awaited<ReturnType<typeof listarReservas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarReservas<TData = Awaited<ReturnType<typeof listarReservas>>, TError = ErrorResponse>(
 params?: ListarReservasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReservas>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar reservas con paginación y filtro por fecha
 */

export function useListarReservas<TData = Awaited<ReturnType<typeof listarReservas>>, TError = ErrorResponse>(
 params?: ListarReservasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReservas>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarReservasQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Crear una reserva
 */
export type crearReservaResponse201 = {
  data: Reserva
  status: 201
}

export type crearReservaResponse401 = {
  data: ErrorResponse
  status: 401
}

export type crearReservaResponse422 = {
  data: ErrorResponse
  status: 422
}

export type crearReservaResponseSuccess = (crearReservaResponse201) & {
  headers: Headers;
};
export type crearReservaResponseError = (crearReservaResponse401 | crearReservaResponse422) & {
  headers: Headers;
};

export type crearReservaResponse = (crearReservaResponseSuccess | crearReservaResponseError)

export const getCrearReservaUrl = () => {




  return `/api/reservas`
}

export const crearReserva = async (crearReservaRequest: CrearReservaRequest, options?: RequestInit): Promise<crearReservaResponse> => {

  return customInstance<crearReservaResponse>(getCrearReservaUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      crearReservaRequest,)
  }
);}




export const getCrearReservaMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof crearReserva>>, TError,{data: CrearReservaRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof crearReserva>>, TError,{data: CrearReservaRequest}, TContext> => {

const mutationKey = ['crearReserva'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof crearReserva>>, {data: CrearReservaRequest}> = (props) => {
          const {data} = props ?? {};

          return  crearReserva(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CrearReservaMutationResult = NonNullable<Awaited<ReturnType<typeof crearReserva>>>
    export type CrearReservaMutationBody = CrearReservaRequest
    export type CrearReservaMutationError = ErrorResponse

    /**
 * @summary Crear una reserva
 */
export const useCrearReserva = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof crearReserva>>, TError,{data: CrearReservaRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof crearReserva>>,
        TError,
        {data: CrearReservaRequest},
        TContext
      > => {
      return useMutation(getCrearReservaMutationOptions(options), queryClient);
    }

/**
 * @summary Conteo de reservas del mes y día actual — para el widget de Home
 */
export type conteoReservasResponse200 = {
  data: ReservasConteo
  status: 200
}

export type conteoReservasResponse401 = {
  data: ErrorResponse
  status: 401
}

export type conteoReservasResponseSuccess = (conteoReservasResponse200) & {
  headers: Headers;
};
export type conteoReservasResponseError = (conteoReservasResponse401) & {
  headers: Headers;
};

export type conteoReservasResponse = (conteoReservasResponseSuccess | conteoReservasResponseError)

export const getConteoReservasUrl = () => {




  return `/api/reservas/conteo`
}

export const conteoReservas = async ( options?: RequestInit): Promise<conteoReservasResponse> => {

  return customInstance<conteoReservasResponse>(getConteoReservasUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getConteoReservasQueryKey = () => {
    return [
    `/api/reservas/conteo`
    ] as const;
    }


export const getConteoReservasQueryOptions = <TData = Awaited<ReturnType<typeof conteoReservas>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conteoReservas>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConteoReservasQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof conteoReservas>>> = ({ signal }) => conteoReservas({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof conteoReservas>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConteoReservasQueryResult = NonNullable<Awaited<ReturnType<typeof conteoReservas>>>
export type ConteoReservasQueryError = ErrorResponse


export function useConteoReservas<TData = Awaited<ReturnType<typeof conteoReservas>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof conteoReservas>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof conteoReservas>>,
          TError,
          Awaited<ReturnType<typeof conteoReservas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConteoReservas<TData = Awaited<ReturnType<typeof conteoReservas>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conteoReservas>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof conteoReservas>>,
          TError,
          Awaited<ReturnType<typeof conteoReservas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConteoReservas<TData = Awaited<ReturnType<typeof conteoReservas>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conteoReservas>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Conteo de reservas del mes y día actual — para el widget de Home
 */

export function useConteoReservas<TData = Awaited<ReturnType<typeof conteoReservas>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof conteoReservas>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConteoReservasQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Obtener una reserva por ID
 */
export type obtenerReservaResponse200 = {
  data: Reserva
  status: 200
}

export type obtenerReservaResponse401 = {
  data: ErrorResponse
  status: 401
}

export type obtenerReservaResponse404 = {
  data: ErrorResponse
  status: 404
}

export type obtenerReservaResponseSuccess = (obtenerReservaResponse200) & {
  headers: Headers;
};
export type obtenerReservaResponseError = (obtenerReservaResponse401 | obtenerReservaResponse404) & {
  headers: Headers;
};

export type obtenerReservaResponse = (obtenerReservaResponseSuccess | obtenerReservaResponseError)

export const getObtenerReservaUrl = (id: string,) => {




  return `/api/reservas/${id}`
}

export const obtenerReserva = async (id: string, options?: RequestInit): Promise<obtenerReservaResponse> => {

  return customInstance<obtenerReservaResponse>(getObtenerReservaUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerReservaQueryKey = (id: string,) => {
    return [
    `/api/reservas/${id}`
    ] as const;
    }


export const getObtenerReservaQueryOptions = <TData = Awaited<ReturnType<typeof obtenerReserva>>, TError = ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerReserva>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerReservaQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerReserva>>> = ({ signal }) => obtenerReserva(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerReserva>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerReservaQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerReserva>>>
export type ObtenerReservaQueryError = ErrorResponse


export function useObtenerReserva<TData = Awaited<ReturnType<typeof obtenerReserva>>, TError = ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerReserva>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerReserva>>,
          TError,
          Awaited<ReturnType<typeof obtenerReserva>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerReserva<TData = Awaited<ReturnType<typeof obtenerReserva>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerReserva>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerReserva>>,
          TError,
          Awaited<ReturnType<typeof obtenerReserva>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerReserva<TData = Awaited<ReturnType<typeof obtenerReserva>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerReserva>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener una reserva por ID
 */

export function useObtenerReserva<TData = Awaited<ReturnType<typeof obtenerReserva>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerReserva>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerReservaQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Actualizar una reserva
 */
export type actualizarReservaResponse200 = {
  data: Reserva
  status: 200
}

export type actualizarReservaResponse401 = {
  data: ErrorResponse
  status: 401
}

export type actualizarReservaResponse404 = {
  data: ErrorResponse
  status: 404
}

export type actualizarReservaResponseSuccess = (actualizarReservaResponse200) & {
  headers: Headers;
};
export type actualizarReservaResponseError = (actualizarReservaResponse401 | actualizarReservaResponse404) & {
  headers: Headers;
};

export type actualizarReservaResponse = (actualizarReservaResponseSuccess | actualizarReservaResponseError)

export const getActualizarReservaUrl = (id: string,) => {




  return `/api/reservas/${id}`
}

export const actualizarReserva = async (id: string,
    actualizarReservaRequest: ActualizarReservaRequest, options?: RequestInit): Promise<actualizarReservaResponse> => {

  return customInstance<actualizarReservaResponse>(getActualizarReservaUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      actualizarReservaRequest,)
  }
);}




export const getActualizarReservaMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actualizarReserva>>, TError,{id: string;data: ActualizarReservaRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof actualizarReserva>>, TError,{id: string;data: ActualizarReservaRequest}, TContext> => {

const mutationKey = ['actualizarReserva'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof actualizarReserva>>, {id: string;data: ActualizarReservaRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  actualizarReserva(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActualizarReservaMutationResult = NonNullable<Awaited<ReturnType<typeof actualizarReserva>>>
    export type ActualizarReservaMutationBody = ActualizarReservaRequest
    export type ActualizarReservaMutationError = ErrorResponse

    /**
 * @summary Actualizar una reserva
 */
export const useActualizarReserva = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actualizarReserva>>, TError,{id: string;data: ActualizarReservaRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof actualizarReserva>>,
        TError,
        {id: string;data: ActualizarReservaRequest},
        TContext
      > => {
      return useMutation(getActualizarReservaMutationOptions(options), queryClient);
    }

/**
 * @summary Eliminar una reserva
 */
export type eliminarReservaResponse204 = {
  data: void
  status: 204
}

export type eliminarReservaResponse401 = {
  data: ErrorResponse
  status: 401
}

export type eliminarReservaResponse404 = {
  data: ErrorResponse
  status: 404
}

export type eliminarReservaResponseSuccess = (eliminarReservaResponse204) & {
  headers: Headers;
};
export type eliminarReservaResponseError = (eliminarReservaResponse401 | eliminarReservaResponse404) & {
  headers: Headers;
};

export type eliminarReservaResponse = (eliminarReservaResponseSuccess | eliminarReservaResponseError)

export const getEliminarReservaUrl = (id: string,) => {




  return `/api/reservas/${id}`
}

export const eliminarReserva = async (id: string, options?: RequestInit): Promise<eliminarReservaResponse> => {

  return customInstance<eliminarReservaResponse>(getEliminarReservaUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEliminarReservaMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eliminarReserva>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof eliminarReserva>>, TError,{id: string}, TContext> => {

const mutationKey = ['eliminarReserva'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eliminarReserva>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  eliminarReserva(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EliminarReservaMutationResult = NonNullable<Awaited<ReturnType<typeof eliminarReserva>>>

    export type EliminarReservaMutationError = ErrorResponse

    /**
 * @summary Eliminar una reserva
 */
export const useEliminarReserva = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eliminarReserva>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eliminarReserva>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getEliminarReservaMutationOptions(options), queryClient);
    }

/**
 * @summary Listar ventas con paginación y filtros de fecha
 */
export type listarVentasResponse200 = {
  data: VentasPaginadas
  status: 200
}

export type listarVentasResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listarVentasResponseSuccess = (listarVentasResponse200) & {
  headers: Headers;
};
export type listarVentasResponseError = (listarVentasResponse401) & {
  headers: Headers;
};

export type listarVentasResponse = (listarVentasResponseSuccess | listarVentasResponseError)

export const getListarVentasUrl = (params?: ListarVentasParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/ventas?${stringifiedParams}` : `/api/ventas`
}

export const listarVentas = async (params?: ListarVentasParams, options?: RequestInit): Promise<listarVentasResponse> => {

  return customInstance<listarVentasResponse>(getListarVentasUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarVentasQueryKey = (params?: ListarVentasParams,) => {
    return [
    `/api/ventas`, ...(params ? [params] : [])
    ] as const;
    }


export const getListarVentasQueryOptions = <TData = Awaited<ReturnType<typeof listarVentas>>, TError = ErrorResponse>(params?: ListarVentasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarVentas>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarVentasQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarVentas>>> = ({ signal }) => listarVentas(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarVentas>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarVentasQueryResult = NonNullable<Awaited<ReturnType<typeof listarVentas>>>
export type ListarVentasQueryError = ErrorResponse


export function useListarVentas<TData = Awaited<ReturnType<typeof listarVentas>>, TError = ErrorResponse>(
 params: undefined |  ListarVentasParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarVentas>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarVentas>>,
          TError,
          Awaited<ReturnType<typeof listarVentas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarVentas<TData = Awaited<ReturnType<typeof listarVentas>>, TError = ErrorResponse>(
 params?: ListarVentasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarVentas>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarVentas>>,
          TError,
          Awaited<ReturnType<typeof listarVentas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarVentas<TData = Awaited<ReturnType<typeof listarVentas>>, TError = ErrorResponse>(
 params?: ListarVentasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarVentas>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar ventas con paginación y filtros de fecha
 */

export function useListarVentas<TData = Awaited<ReturnType<typeof listarVentas>>, TError = ErrorResponse>(
 params?: ListarVentasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarVentas>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarVentasQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Crear una venta
 */
export type crearVentaResponse201 = {
  data: Venta
  status: 201
}

export type crearVentaResponse401 = {
  data: ErrorResponse
  status: 401
}

export type crearVentaResponse422 = {
  data: ErrorResponse
  status: 422
}

export type crearVentaResponseSuccess = (crearVentaResponse201) & {
  headers: Headers;
};
export type crearVentaResponseError = (crearVentaResponse401 | crearVentaResponse422) & {
  headers: Headers;
};

export type crearVentaResponse = (crearVentaResponseSuccess | crearVentaResponseError)

export const getCrearVentaUrl = () => {




  return `/api/ventas`
}

export const crearVenta = async (crearVentaRequest: CrearVentaRequest, options?: RequestInit): Promise<crearVentaResponse> => {

  return customInstance<crearVentaResponse>(getCrearVentaUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      crearVentaRequest,)
  }
);}




export const getCrearVentaMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof crearVenta>>, TError,{data: CrearVentaRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof crearVenta>>, TError,{data: CrearVentaRequest}, TContext> => {

const mutationKey = ['crearVenta'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof crearVenta>>, {data: CrearVentaRequest}> = (props) => {
          const {data} = props ?? {};

          return  crearVenta(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CrearVentaMutationResult = NonNullable<Awaited<ReturnType<typeof crearVenta>>>
    export type CrearVentaMutationBody = CrearVentaRequest
    export type CrearVentaMutationError = ErrorResponse

    /**
 * @summary Crear una venta
 */
export const useCrearVenta = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof crearVenta>>, TError,{data: CrearVentaRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof crearVenta>>,
        TError,
        {data: CrearVentaRequest},
        TContext
      > => {
      return useMutation(getCrearVentaMutationOptions(options), queryClient);
    }

/**
 * @summary Obtener una venta por ID
 */
export type obtenerVentaResponse200 = {
  data: Venta
  status: 200
}

export type obtenerVentaResponse401 = {
  data: ErrorResponse
  status: 401
}

export type obtenerVentaResponse404 = {
  data: ErrorResponse
  status: 404
}

export type obtenerVentaResponseSuccess = (obtenerVentaResponse200) & {
  headers: Headers;
};
export type obtenerVentaResponseError = (obtenerVentaResponse401 | obtenerVentaResponse404) & {
  headers: Headers;
};

export type obtenerVentaResponse = (obtenerVentaResponseSuccess | obtenerVentaResponseError)

export const getObtenerVentaUrl = (id: string,) => {




  return `/api/ventas/${id}`
}

export const obtenerVenta = async (id: string, options?: RequestInit): Promise<obtenerVentaResponse> => {

  return customInstance<obtenerVentaResponse>(getObtenerVentaUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerVentaQueryKey = (id: string,) => {
    return [
    `/api/ventas/${id}`
    ] as const;
    }


export const getObtenerVentaQueryOptions = <TData = Awaited<ReturnType<typeof obtenerVenta>>, TError = ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerVenta>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerVentaQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerVenta>>> = ({ signal }) => obtenerVenta(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerVenta>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerVentaQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerVenta>>>
export type ObtenerVentaQueryError = ErrorResponse


export function useObtenerVenta<TData = Awaited<ReturnType<typeof obtenerVenta>>, TError = ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerVenta>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerVenta>>,
          TError,
          Awaited<ReturnType<typeof obtenerVenta>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerVenta<TData = Awaited<ReturnType<typeof obtenerVenta>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerVenta>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerVenta>>,
          TError,
          Awaited<ReturnType<typeof obtenerVenta>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerVenta<TData = Awaited<ReturnType<typeof obtenerVenta>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerVenta>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener una venta por ID
 */

export function useObtenerVenta<TData = Awaited<ReturnType<typeof obtenerVenta>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerVenta>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerVentaQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Eliminar una venta
 */
export type eliminarVentaResponse204 = {
  data: void
  status: 204
}

export type eliminarVentaResponse401 = {
  data: ErrorResponse
  status: 401
}

export type eliminarVentaResponse404 = {
  data: ErrorResponse
  status: 404
}

export type eliminarVentaResponseSuccess = (eliminarVentaResponse204) & {
  headers: Headers;
};
export type eliminarVentaResponseError = (eliminarVentaResponse401 | eliminarVentaResponse404) & {
  headers: Headers;
};

export type eliminarVentaResponse = (eliminarVentaResponseSuccess | eliminarVentaResponseError)

export const getEliminarVentaUrl = (id: string,) => {




  return `/api/ventas/${id}`
}

export const eliminarVenta = async (id: string, options?: RequestInit): Promise<eliminarVentaResponse> => {

  return customInstance<eliminarVentaResponse>(getEliminarVentaUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEliminarVentaMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eliminarVenta>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof eliminarVenta>>, TError,{id: string}, TContext> => {

const mutationKey = ['eliminarVenta'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eliminarVenta>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  eliminarVenta(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EliminarVentaMutationResult = NonNullable<Awaited<ReturnType<typeof eliminarVenta>>>

    export type EliminarVentaMutationError = ErrorResponse

    /**
 * @summary Eliminar una venta
 */
export const useEliminarVenta = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eliminarVenta>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eliminarVenta>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getEliminarVentaMutationOptions(options), queryClient);
    }
